root = "."
tmp_dir = "tmp"

[build]
  cmd = "cd frontend && npm run build && cd .. && go build -ldflags '-X \"github.com/hydrocode-de/datailama/internal/version.BuildTime={{.BuildTime}}\" -X \"github.com/hydrocode-de/datailama/internal/version.GitCommit={{.GitCommit}}\"' -o ./tmp/main ."
  bin = "./tmp/main serve"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules", "internal/web/site/frontend", ".svelte-kit"]
  include_ext = ["go", "tpl", "tmpl", "html", "templ", "svelte", "js", "ts", "css"]
  exclude_regex = ["_test.go", "_templ.go"] 