root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -ldflags '-X \"github.com/hydrocode-de/datailama/internal/version.BuildTime={{.BuildTime}}\" -X \"github.com/hydrocode-de/datailama/internal/version.GitCommit={{.GitCommit}}\"' -o ./tmp/main ."
  bin = "./tmp/main serve"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test.go"] 